# -*- coding: utf-8 -*-
"""ISM4402_workbookA3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D4Q7kT_1oxG2pipdhL5bOpdSze63WMYY
"""

import pandas as pd
names = ['Bob','Jessica','Mary','John','Mel']
grades = [76,-2,77,78,101]
GradeList = zip(names,grades)
df = pd.DataFrame(data = GradeList,
columns=['Names', 'Grades'])

df

df.loc[df['Grades'] <= 100]

df.loc[(df['Grades'] >= 100,'Grades')] = 100

df

df.loc[df['Grades'] < 0]

df.loc[(df['Grades'] < 0,'Grades')] = 0

df
